// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

// Error Codes
const ERROR_CODES = {
  // Authentication Errors
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // Validation Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  INVALID_EMAIL: "INVALID_EMAIL",

  // Resource Errors
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  // Instance Errors
  INSTANCE_NOT_FOUND: "INSTANCE_NOT_FOUND",
  INSTANCE_NOT_CONNECTED: "INSTANCE_NOT_CONNECTED",
  INSTANCE_ALREADY_EXISTS: "INSTANCE_ALREADY_EXISTS",
  INSTANCE_LIMIT_REACHED: "INSTANCE_LIMIT_REACHED",
  INSTANCE_CONNECTION_FAILED: "INSTANCE_CONNECTION_FAILED",

  // API Key Errors
  API_KEY_INVALID: "API_KEY_INVALID",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  API_KEY_REVOKED: "API_KEY_REVOKED",

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Message Errors
  MESSAGE_SEND_FAILED: "MESSAGE_SEND_FAILED",
  MESSAGE_INVALID_RECIPIENT: "MESSAGE_INVALID_RECIPIENT",
  MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG",

  // Webhook Errors
  WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED",
  WEBHOOK_INVALID_URL: "WEBHOOK_INVALID_URL",

  // User Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_HAS_DEPENDENCIES: "USER_HAS_DEPENDENCIES",
  INVALID_OPERATION: "INVALID_OPERATION",

  // Subscription Errors
  SUBSCRIPTION_LIMIT_EXCEEDED: "SUBSCRIPTION_LIMIT_EXCEEDED",
  SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",

  // System Errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
};

// User Roles
const USER_ROLES = {
  ADMINISTRATOR: "ADMINISTRATOR",
  USER: "USER",
};

// Subscription Tiers
const SUBSCRIPTION_TIERS = {
  BASIC: "BASIC",
  PRO: "PRO",
  MAX: "MAX",
};

// Instance Status
const INSTANCE_STATUS = {
  INIT: "INIT", // Initializing connection
  QR_REQUIRED: "QR_REQUIRED", // QR code must be scanned to log in
  CONNECTED: "CONNECTED", // WhatsApp session is active
  DISCONNECTED: "DISCONNECTED", // Phone disconnected, or session terminated
  RECONNECTING: "RECONNECTING", // Trying to re-establish session
  ERROR: "ERROR", // Fatal error (e.g., banned, QR scan expired)
};

const SOCKET_EVENTS = {
  INSTANCE_STATUS_CHANGED: "instance:status:changed",
  INSTANCE_QR_GENERATED: "instance:qr:generated",
  INSTANCE_CONNECTED: "instance:connected",
  INSTANCE_DISCONNECTED: "instance:disconnected",
  INSTANCE_ERROR: "instance:error",
  SUBSCRIPTION_STATS: "subscription:stats:updated",
};

// Usage Types
const USAGE_TYPES = {
  MESSAGES_SENT: "MESSAGES_SENT",
  MESSAGES_RECEIVED: "MESSAGES_RECEIVED",
  API_CALLS: "API_CALLS",
  WEBHOOK_CALLS: "WEBHOOK_CALLS",
  STORAGE_USED: "STORAGE_USED",
};

// Message Types
const MESSAGE_TYPES = {
  TEXT: "text",
  IMAGE: "image",
  DOCUMENT: "document",
  AUDIO: "audio",
  VIDEO: "video",
  LOCATION: "location",
  CONTACT: "contact",
};

// Webhook Events
const WEBHOOK_EVENTS = {
  MESSAGE: "message",
  MESSAGE_STATUS: "message_status",
  CONNECTION_STATUS: "connection_status",
  QR_CODE: "qr_code",
  INSTANCE_STATUS: "instance_status",
};

// API Permissions
const API_PERMISSIONS = {
  MESSAGE_SEND: "message:send",
  MESSAGE_READ: "message:read",
  CONTACT_CHECK: "contact:check",
  CONTACT_MANAGE: "contact:manage",
  INSTANCE_INFO: "instance:info",
  STATS_READ: "stats:read",
  WEBHOOK_MANAGE: "webhook:manage",
};

// Audit Actions
const AUDIT_ACTIONS = {
  // User Actions
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  // Instance Actions
  INSTANCE_CREATED: "INSTANCE_CREATED",
  INSTANCE_UPDATED: "INSTANCE_UPDATED",
  INSTANCE_DELETED: "INSTANCE_DELETED",
  INSTANCE_CONNECTED: "INSTANCE_CONNECTED",
  INSTANCE_DISCONNECTED: "INSTANCE_DISCONNECTED",
  INSTANCE_LOGGED_OUT: "INSTANCE_LOGGED_OUT",
  INSTANCE_RESTARTED: "INSTANCE_RESTARTED",

  // API Key Actions
  API_KEY_CREATED: "API_KEY_CREATED",
  API_KEY_UPDATED: "API_KEY_UPDATED",
  API_KEY_DELETED: "API_KEY_DELETED",
  API_KEY_USED: "API_KEY_USED",

  // Message Actions
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_FAILED: "MESSAGE_FAILED",

  // Webhook Actions
  WEBHOOK_CONFIGURED: "WEBHOOK_CONFIGURED",
  WEBHOOK_UPDATED: "WEBHOOK_UPDATED",
  WEBHOOK_DELETED: "WEBHOOK_DELETED",
  WEBHOOK_DELIVERED: "WEBHOOK_DELIVERED",
  WEBHOOK_FAILED: "WEBHOOK_FAILED",

  // Security Actions
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
};

// Default Settings
const DEFAULTS = {
  PAGINATION: {
    PAGE: 1,
    PER_PAGE: 20,
    MAX_PER_PAGE: 100,
  },

  RATE_LIMITS: {
    BASIC: 1000,
    PRO: 5000,
    MAX: 10000,
  },

  TIMEOUTS: {
    QR_CODE_EXPIRY: 2 * 60 * 1000, // 2 minutes
    CONNECTION_TIMEOUT: 30 * 1000, // 30 seconds
    WEBHOOK_TIMEOUT: 10 * 1000, // 10 seconds
  },

  MESSAGE_LIMITS: {
    TEXT_MAX_LENGTH: 4096,
    CAPTION_MAX_LENGTH: 1024,
    FILENAME_MAX_LENGTH: 255,
  },
};

// Baileys Connection States
const BAILEYS_CONNECTION_STATE = {
  CLOSE: "close",
  CONNECTING: "connecting",
  OPEN: "open",
};

// Baileys Disconnect Reasons
const BAILEYS_DISCONNECT_REASONS = {
  CONNECTION_CLOSED: "connectionClosed",
  CONNECTION_LOST: "connectionLost",
  CONNECTION_REPLACED: "connectionReplaced",
  TIMED_OUT: "timedOut",
  LOGGED_OUT: "loggedOut",
  BAD_SESSION: "badSession",
  RESTART_REQUIRED: "restartRequired",
};

export {
  HTTP_STATUS,
  ERROR_CODES,
  USER_ROLES,
  SUBSCRIPTION_TIERS,
  INSTANCE_STATUS,
  SOCKET_EVENTS,
  USAGE_TYPES,
  MESSAGE_TYPES,
  WEBHOOK_EVENTS,
  API_PERMISSIONS,
  AUDIT_ACTIONS,
  DEFAULTS,
  BAILEYS_CONNECTION_STATE,
  BAILEYS_DISCONNECT_REASONS,
};
